// This file configures Firebase SDK options. Auto-generated by FlutterFire CLI.
// DO NOT edit this file manually.

import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_ANDROID_API_KEY_REPLACE_WITH_REAL_KEY',
    appId: 'PLACEHOLDER_ANDROID_APP_ID',
    messagingSenderId: 'PLACEHOLDER_MESSAGING_SENDER_ID',
    projectId: 'shougaku-kore-doutoku',
    databaseURL: 'https://shougaku-kore-doutoku.firebaseio.com',
    storageBucket: 'shougaku-kore-doutoku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_IOS_API_KEY_REPLACE_WITH_REAL_KEY',
    appId: 'PLACEHOLDER_IOS_APP_ID',
    messagingSenderId: 'PLACEHOLDER_MESSAGING_SENDER_ID',
    projectId: 'shougaku-kore-doutoku',
    databaseURL: 'https://shougaku-kore-doutoku.firebaseio.com',
    storageBucket: 'shougaku-kore-doutoku.appspot.com',
    iosClientId: 'PLACEHOLDER_IOS_CLIENT_ID',
    iosBundleId: 'jp.petitworks.shougakuKoreDoutoku',
  );
}

// TODO: Replace the above placeholders with actual Firebase credentials
